site_name: some notes
site_url: https://zhappyhammer.github.io/notes
nav:
    - 前言: index.md


theme:
    name: material
    favicon: images/favicon.ico
    logo: images/logo.jpeg
    language: zh
    features:
        - content.code.copy
        - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
        - navigation.tabs.sticky # 滚动时隐藏顶部nav，配合navigation.tabs使用
        - navigation.tracking # 在url中使用标题定位锚点
        # - navigation.expand # 不折叠左侧nav节点
        # - navigation.sections # nav节点缩进
        - navigation.path
        - navigation.top # 一键回顶部
        - navigation.instant # 启用即时加载
        - navigation.indexes
        - toc.follow
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    # 这个是设置页面支持latex公式的，下面四行都是
    - pymdownx.arithmatex:
        generic: true
extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
